language: python
sudo: false

python:
  - 3.6
  - 3.8
  - 3.9

install:
  - pip install -U pip
  - pip install codecov
  - pip install .[full]

script:
  - coverage run setup.py test

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
  - codecov
