language: python
sudo: false

python:
  - 2.7
  - 3.6

install:
  - pip install -U pip
  - pip install .[tests]

script:
  - py.test -v test_pyout.py

notifications:
  email:
    on_success: never
    on_failure: always
