language: python
sudo: false

python:
  - 2.7
  - 3.6

install:
  - pip install -U pip
  - pip install .[full]

script:
  - python setup.py test

notifications:
  email:
    on_success: never
    on_failure: always
