language: python
sudo: false

python:
  - 3.4
  - 3.6
env:
  - pip_schema=full
  - pip_schema=core

install:
  - pip install -U pip
  - pip install codecov
  - pip install .[$pip_schema]
  - pip install .[tests]

script:
  - coverage run setup.py test

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
  - codecov
